### ISSUE TITLE
How can i install it?

### ISSUE THREAD

**Issue by Erkam246** [SpaceboyRoss01/cc-dos#1]

**Comment by RossComputerGuy** [comment]
copy the files from src/Disk to your computer craft's hard drive

**Comment by RossComputerGuy** [comment]
Here is the official wiki page https://github.com/SpaceboyRoss01/cc-dos/wiki/Installation

**Comment by Erkam246** [comment]
pastebin link?

**Comment by RossComputerGuy** [comment]
There isn't one, yet

**Comment by Erkam246** [comment]
ok..
